on:
  pull_request_target:

permissions:
  contents: read

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - run: cat "$GITHUB_PATH"
    - uses: hmarr/debug-action@v2

  job1:
    if: contains(github.event.issue.labels.*.name, 'ok')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
  job2:
    if: github.event.label.name == 'ok'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
  job3:
    if: github.actor == 'ok'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
  job4:
    if: github.actor == 'ok' || true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
  job5:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
